//! `SeaORM` Entity. Generated by sea-orm-codegen 0.11.3

use sea_orm::entity::prelude::*;

#[derive(Clone, Debug, PartialEq, DeriveEntityModel, Eq)]
#[sea_orm(table_name = "relay_node")]
pub struct Model {
    #[sea_orm(primary_key, auto_increment = false)]
    pub oid: String,
    pub hub: String,
    pub agent_name: String,
    pub service_name: String,
    pub r#type: String,
    pub online: bool,
    pub last_online_time: bool,
}

#[derive(Copy, Clone, Debug, EnumIter, DeriveRelation)]
pub enum Relation {}

impl ActiveModelBehavior for ActiveModel {}
